# Rust code formatting configuration file
# For more configuration options, see: https://rust-lang.github.io/rustfmt/

# Indentation settings
tab_spaces = 4                    # Use spaces for indentation, 4 spaces
edition = "2024"                  # Use Rust 2024 edition (latest)

# Line length settings
max_width = 100                   # Maximum line length
hard_tabs = false                 # Use spaces instead of tabs
newline_style = "Unix"            # Use Unix-style line endings

# Import settings
reorder_imports = true            # Reorder imports
reorder_modules = true            # Reorder modules

# Function settings
fn_call_width = 60                # Function call width
fn_params_layout = "Tall"         # Function parameter layout

# Expression settings
match_arm_leading_pipes = "Never" # Match arm leading pipes
match_block_trailing_comma = false # Match block trailing comma

# Other settings
merge_derives = true              # Merge derive attributes
use_small_heuristics = "Default"  # Use heuristic rules

# Chain call settings
chain_width = 60                  # Chain call width

# Array settings
array_width = 60                  # Array width